server:
  port: 9090
  servlet:
    session:
      cookie:
        name: SESSIONDEMO
security:
  oauth2:
    client:
      client-id: client2
      client-secret: secret
      access-token-uri: http://localhost:8080/oauth/token
      user-authorization-uri: http://localhost:8080/oauth/authorize
      scope: read
    resource:
      user-info-uri: http://localhost:8080/User/me
      jwt:
        key-uri: http://localhost:8080/oauth/token_key
        key-value: XYVIDEOOAUTHSERVERSIGNKEY
